watch-files:
  # Changes in which files cause reruns
  - 'test/**/*.ts'
  - 'api/**/*.ts'
require:
  - 'ts-node/register'
  - 'tsconfig-paths/register'
  - 'dotenv/config'
extension:
  - 'ts'
spec:
  # Where to look for tests
  - 'api/**/*.test.ts'
