# This file is not finished yet. Environment vars could not be loaded.
version: '3.9'
services:
  family:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
